name         'puppet-module-tweaks'
version      '0.0.1'
source       'git@github.com:kylefu8/puppet-module-tweaks.git'
author       'Kyle Fu'
license      'Apache License, Version 2.0'
summary      'Linux Server tweaks'
description  'Collection of Linux server tweaks'
project_page 'https://github.com/kylefu8/puppet-module-tweaks'

dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'ghoneycutt/common', '>= 1.0.0'
